import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  //table jabatan
  const admin = await prisma.jabatan.upsert({
    where: { namaJabatan: "Admin" },
    update: {},
    create: {
      namaJabatan: "Admin",
    },
  });

  const staffRm = await prisma.jabatan.upsert({
    where: { namaJabatan: "Staff Rekam Medis" },
    update: {},
    create: {
      namaJabatan: "Staff Rekam Medis",
    },
  });

  const dokter = await prisma.jabatan.upsert({
    where: { namaJabatan: "Dokter" },
    update: {},
    create: {
      namaJabatan: "Dokter",
    },
  });

  console.log("Jabatan ditambahkan: ", [
    admin.namaJabatan,
    staffRm.namaJabatan,
    dokter.namaJabatan,
  ]);

  //tabel user
  const moyo = await prisma.user.upsert({
    where: { username: "moyo" },
    update: {},
    create: {
      username: "moyo",
      email: "moyo@gmail.com",
      password: "$2a$10$ZXlNml7VZUVjI1ch8V3C1eAGLfGFMMXujFhotmlumVjAtJHJdwa.a", //moyomoyo
      namaLengkap: "Wismoyo Bagas Laksono",
      idJabatan: 1,
    },
  });

  const filsa = await prisma.user.upsert({
    where: { username: "filsacantik" },
    update: {},
    create: {
      username: "filsacantik",
      email: "filsa0817@gmail.com",
      password: "$2a$10$7nLV8O4KRTdb9sw3J54nhe3yG6vw3OqAu8kypEd5AgburyGpPmGN6", //filsasayang
      namaLengkap: "Filsa Agustina",
      idJabatan: 2,
    },
  });

  const brian = await prisma.user.upsert({
    where: { username: "brian" },
    update: {},
    create: {
      username: "brian",
      email: "briankece@gmail.com",
      password: "$2a$10$0HQJJskk3mGBxwrT7gmGbOhSixEzhbjBwB/EbfMOLDKyRErz48VbO", //briancool
      namaLengkap: "Brian Stavish Quac",
      idJabatan: 3,
    },
  });

  console.log("User ditambahkan: ", [
    moyo.username,
    filsa.username,
    brian.username,
  ]);

  await prisma.pasien.createMany({
    data: [
      {
        noRm: "202400001",
        idIdentitas: "ID001",
        wna: "WNI",
        namaLengkap: "Budi Santoso",
        jenisKelamin: "Laki-laki",
        tglLahir: "1990-01-15T00:00:00.000Z",
        tmptLahir: "Jakarta",
        agama: "Islam",
        alamat: "Jl. Merdeka No. 10",
        provinsi: "DKI Jakarta",
        rt: "01",
        rw: "02",
        kecamatan: "Menteng",
        kelurahan: "Gambir",
        pekerjaan: "Pegawai Negeri",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "O",
        noAsuransi: "ASUR001",
        ibuKandung: "Siti Aminah",
        noTlp: "081234567890",
      },
      {
        noRm: "202400002",
        idIdentitas: "ID002",
        wna: "WNI",
        namaLengkap: "Siti Nurhaliza",
        jenisKelamin: "Perempuan",
        tglLahir: "1985-05-20T00:00:00.000Z",
        tmptLahir: "Bandung",
        agama: "Islam",
        alamat: "Jl. Kebangkitan No. 20",
        provinsi: "Jawa Barat",
        rt: "03",
        rw: "04",
        kecamatan: "Cimahi",
        kelurahan: "Cimahi Utara",
        pekerjaan: "Dokter",
        pernikahan: "Belum Menikah",
        pendidikan: "S2",
        golDarah: "A",
        noAsuransi: "ASUR002",
        ibuKandung: "Fatimah",
        noTlp: "082345678901",
      },
      {
        noRm: "202400003",
        idIdentitas: "ID003",
        wna: "WNI",
        namaLengkap: "Andi Prasetyo",
        jenisKelamin: "Laki-laki",
        tglLahir: "1992-08-10T00:00:00.000Z",
        tmptLahir: "Yogyakarta",
        agama: "Kristen",
        alamat: "Jl. Soekarno Hatta No. 15",
        provinsi: "DI Yogyakarta",
        rt: "05",
        rw: "06",
        kecamatan: "Kota Yogyakarta",
        kelurahan: "Ngampilan",
        pekerjaan: "Wirausaha",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "B",
        noAsuransi: "ASUR003",
        ibuKandung: "Dewi Sartika",
        noTlp: "083456789012",
      },
      {
        noRm: "202400004",
        idIdentitas: "ID004",
        wna: "WNI",
        namaLengkap: "Dewi Lestari",
        jenisKelamin: "Perempuan",
        tglLahir: "1995-03-30T00:00:00.000Z",
        tmptLahir: "Surabaya",
        agama: "Hindu",
        alamat: "Jl. Merpati No. 4",
        provinsi: "Jawa Timur",
        rt: "07",
        rw: "08",
        kecamatan: "Tenggilis Mejoyo",
        kelurahan: "Tenggilis Mejoyo",
        pekerjaan: "Mahasiswa",
        pernikahan: "Belum Menikah",
        pendidikan: "S1",
        golDarah: "O",
        noAsuransi: "ASUR004",
        ibuKandung: "Rina Hartati",
        noTlp: "084567890123",
      },
      {
        noRm: "202400005",
        idIdentitas: "ID005",
        wna: "WNI",
        namaLengkap: "Fajar Pramudito",
        jenisKelamin: "Laki-laki",
        tglLahir: "1988-12-12T00:00:00.000Z",
        tmptLahir: "Semarang",
        agama: "Kristen",
        alamat: "Jl. Pahlawan No. 21",
        provinsi: "Jawa Tengah",
        rt: "09",
        rw: "10",
        kecamatan: "Semarang Selatan",
        kelurahan: "Pleburan",
        pekerjaan: "Karyawan Swasta",
        pernikahan: "Menikah",
        pendidikan: "D3",
        golDarah: "AB",
        noAsuransi: "ASUR005",
        ibuKandung: "Wati Sudarwati",
        noTlp: "085678901234",
      },
      {
        noRm: "202400006",
        idIdentitas: "ID006",
        wna: "WNI",
        namaLengkap: "Rizky Aditya",
        jenisKelamin: "Laki-laki",
        tglLahir: "1993-11-05T00:00:00.000Z",
        tmptLahir: "Medan",
        agama: "Islam",
        alamat: "Jl. Pendidikan No. 17",
        provinsi: "Sumatera Utara",
        rt: "11",
        rw: "12",
        kecamatan: "Medan Kota",
        kelurahan: "Bangka",
        pekerjaan: "Pengusaha",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "O",
        noAsuransi: "ASUR006",
        ibuKandung: "Nina Nurbaya",
        noTlp: "086789012345",
      },
      {
        noRm: "202400007",
        idIdentitas: "ID007",
        wna: "WNI",
        namaLengkap: "Siti Aisyah",
        jenisKelamin: "Perempuan",
        tglLahir: "1990-06-25T00:00:00.000Z",
        tmptLahir: "Bandung",
        agama: "Islam",
        alamat: "Jl. Cendana No. 15",
        provinsi: "Jawa Barat",
        rt: "03",
        rw: "04",
        kecamatan: "Cibiru",
        kelurahan: "Cibiru Wetan",
        pekerjaan: "Dokter",
        pernikahan: "Menikah",
        pendidikan: "S2",
        golDarah: "A",
        noAsuransi: "ASUR007",
        ibuKandung: "Martha",
        noTlp: "081234567890",
      },
      {
        noRm: "202400008",
        idIdentitas: "ID008",
        wna: "WNI",
        namaLengkap: "Andi Saputra",
        jenisKelamin: "Laki-laki",
        tglLahir: "1985-09-15T00:00:00.000Z",
        tmptLahir: "Yogyakarta",
        agama: "Kristen",
        alamat: "Jl. Merdeka No. 20",
        provinsi: "DI Yogyakarta",
        rt: "01",
        rw: "02",
        kecamatan: "Gamping",
        kelurahan: "Sendangadi",
        pekerjaan: "Wirausaha",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "B",
        noAsuransi: "ASUR008",
        ibuKandung: "Suhartini",
        noTlp: "082345678901",
      },
      {
        noRm: "202400009",
        idIdentitas: "ID009",
        wna: "WNI",
        namaLengkap: "Budi Santoso",
        jenisKelamin: "Laki-laki",
        tglLahir: "1978-04-05T00:00:00.000Z",
        tmptLahir: "Jakarta",
        agama: "Islam",
        alamat: "Jl. Kebon Jeruk No. 35",
        provinsi: "DKI Jakarta",
        rt: "12",
        rw: "13",
        kecamatan: "Kebon Jeruk",
        kelurahan: "Kebon Jeruk",
        pekerjaan: "Guru",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "O",
        noAsuransi: "ASUR009",
        ibuKandung: "Rukmini",
        noTlp: "087654321098",
      },
      {
        noRm: "202400010",
        idIdentitas: "ID010",
        wna: "WNI",
        namaLengkap: "Rina Amelia",
        jenisKelamin: "Perempuan",
        tglLahir: "1995-03-12T00:00:00.000Z",
        tmptLahir: "Medan",
        agama: "Islam",
        alamat: "Jl. Mangga No. 5",
        provinsi: "Sumatera Utara",
        rt: "07",
        rw: "08",
        kecamatan: "Medan Selayang",
        kelurahan: "Selayang I",
        pekerjaan: "Perawat",
        pernikahan: "Belum Menikah",
        pendidikan: "D3",
        golDarah: "AB",
        noAsuransi: "ASUR010",
        ibuKandung: "Rukmini",
        noTlp: "081234567891",
      },
      {
        noRm: "202400011",
        idIdentitas: "ID011",
        wna: "WNI",
        namaLengkap: "Joko Prabowo",
        jenisKelamin: "Laki-laki",
        tglLahir: "1980-12-20T00:00:00.000Z",
        tmptLahir: "Surabaya",
        agama: "Kristen",
        alamat: "Jl. Kenanga No. 25",
        provinsi: "Jawa Timur",
        rt: "02",
        rw: "03",
        kecamatan: "Wonocolo",
        kelurahan: "Wonocolo",
        pekerjaan: "Software Engineer",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "O",
        noAsuransi: "ASUR011",
        ibuKandung: "Dewi",
        noTlp: "085678901234",
      },
      {
        noRm: "202400012",
        idIdentitas: "ID012",
        wna: "WNI",
        namaLengkap: "Nina Sari",
        jenisKelamin: "Perempuan",
        tglLahir: "1992-07-15T00:00:00.000Z",
        tmptLahir: "Bali",
        agama: "Hindu",
        alamat: "Jl. Kamboja No. 10",
        provinsi: "Bali",
        rt: "04",
        rw: "05",
        kecamatan: "Kuta",
        kelurahan: "Kuta",
        pekerjaan: "Marketing",
        pernikahan: "Menikah",
        pendidikan: "S1",
        golDarah: "A",
        noAsuransi: "ASUR012",
        ibuKandung: "Ratih",
        noTlp: "089876543210",
      },
    ],
  });

  console.log("Pasien yang ditambahkan: ", await prisma.pasien.count());
  console.log("Seed data sudah di tambahkan semua!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.log(e);
    await prisma.$disconnect();
    process.exit(1);
  });
